### PR TITLE
feat: Add a lint for unsupported CSS Module selector

### PR DESCRIPTION
**Pull request by kdy1**
Related: https://github.com/vercel/next.js/issues/64299

I made it a parse error because the specification about it is ambiguous thus it's better to bail out.

### CODE REVIEW

File: selectors/parser.rs [hunk 1]
```diff
@@ -198,6 +198,7 @@ pub enum SelectorParseErrorKind<'i> {
   UnexpectedTokenInAttributeSelector(Token<'i>),
   PseudoElementExpectedIdent(Token<'i>),
   UnsupportedPseudoClassOrElement(CowRcStr<'i>),
+  AmbiguosCssModuleClass(CowRcStr<'i>),
```
Comment (mischnic) [inline selectors/parser.rs:201]:
```suggestion
  AmbiguousCssModuleClass(CowRcStr<'i>),
```

File: src/error.rs [hunk 2]
```diff
@@ -257,6 +260,7 @@ impl<'i> fmt::Display for SelectorError<'i> {
       UnexpectedIdent(name) => write!(f, "Unexpected identifier: {}", name),
       UnexpectedTokenInAttributeSelector(token) => write!(f, "Unexpected token in attribute selector: {:?}", token),
       UnsupportedPseudoClassOrElement(name) => write!(f, "Unsupported pseudo class or element: {}", name),
+      AmbiguousCssModuleClass(_) => write!(f, "Ambiguous CSS module class not supoorted"),
```
Comment (devongovett) [inline src/error.rs:263]:
```suggestion
      AmbiguousCssModuleClass(_) => write!(f, "Ambiguous CSS module class not supported"),
```

File: src/selector.rs [hunk 3]
```diff
@@ -190,6 +190,10 @@ impl<'a, 'o, 'i> parcel_selectors::parser::Parser<'i> for SelectorParser<'a, 'o,
       "corner-present" => WebKitScrollbar(WebKitScrollbarPseudoClass::CornerPresent),
       "window-inactive" => WebKitScrollbar(WebKitScrollbarPseudoClass::WindowInactive),
 
+      "local" | "global" => {
```
Comment (devongovett) [inline src/selector.rs:193]: Should we only error if CSS modules are enabled and just pass it through otherwise? Not sure if other tooling might be relying on passthrough of unknown selectors for some reason.

```suggestion
      "local" | "global" if self.options.css_modules.is_some() => {
```

**Review by devongovett — APPROVED** [review]
Thanks! Will do a release tomorrow.

**Comment by kdy1** [comment]
@devongovett Did you do a release?

**Comment by devongovett** [comment]
crates are now published. I ran into a CI build issue for the npm binaries that I still need to fix, but crates should be usable.

**Comment by kdy1** [comment]
Thank you!

**Comment by Baptistemontan** [comment]
Sorry to bother, but this should not have been a patch semver bump but a minor bump, the addition of a new variant to a public enum is breaking some builds. [`trunk`](https://github.com/trunk-rs/trunk) can't be installed at the moment because it tries to make lightningcss alpha 55 works with `parcel_selectors` v0.26.6, and cause this error:

```
error[E0004]: non-exhaustive patterns: `&SelectorParseErrorKind::AmbiguousCssModuleClass(_)` not covered
   --> C:\Users\bapti\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lightningcss-1.0.0-alpha.55\src\error.rs:266:11
    |
266 |     match &err {
    |           ^^^^ pattern `&SelectorParseErrorKind::AmbiguousCssModuleClass(_)` not covered
    |
note: `SelectorParseErrorKind<'_>` defined here
   --> C:\Users\bapti\.cargo\registry\src\index.crates.io-6f17d22bba15001f\parcel_selectors-0.26.6\parser.rs:188:1
    |
188 | pub enum SelectorParseErrorKind<'i> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
201 |   AmbiguousCssModuleClass(CowRcStr<'i>),
    |   ----------------------- not covered
    = note: the matched value is of type `&SelectorParseErrorKind<'_>`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
299 ~       SelectorParseErrorKind::ClassNeedsIdent(t) => SelectorError::ClassNeedsIdent(t.into()),
300 ~       &SelectorParseErrorKind::AmbiguousCssModuleClass(_) => todo!(),
```
