### PR TITLE
Use serde-content instead of private serde types

### LINKED ISSUE #1056: lightningcss no longer compiles with serde 1.0.220 or above
The following error occurs after upgrading to serde 1.0.220+

```
error[E0433]: failed to resolve: could not find `__private` in `serde`
    --> src/properties/mod.rs:992:26
     |
992  |             Content(serde::__private::de::Content<'de>),
     |                            ^^^^^^^^^ could not find `__private` in `serde`
...
1199 | / define_properties! {
1200 | |   "background-color": BackgroundColor(CssColor),
1201 | |   "background-image": BackgroundImage(SmallVec<[Image<'i>; 1]>),
1202 | |   "background-position-x": BackgroundPositionX(SmallVec<[HorizontalPosition; 1]>),
...    |
1615 | |   "color-scheme": ColorScheme(ColorScheme),
1616 | | }
     | |_- in this macro invocation
     |
     = note: this error originates in the macro `define_properties` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Should be related with https://github.com/serde-rs/serde/pull/2608

Similar issue: https://github.com/swc-project/swc/issues/11092

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #1056

Uses the [serde-content](https://crates.io/crates/serde-content) crate to buffer during deserialization instead of internal private serde types, which have now moved.

### CODE REVIEW

File: napi/src/transformer.rs [hunk 1]
```diff
@@ -755,9 +755,8 @@ impl<'de, V: serde::Deserialize<'de>, const IS_VEC: bool> serde::Deserialize<'de
     D: serde::Deserializer<'de>,
   {
     use serde::Deserializer;
-    let content = serde::__private::de::Content::deserialize(deserializer)?;
-    let de: serde::__private::de::ContentRefDeserializer<D::Error> =
-      serde::__private::de::ContentRefDeserializer::new(&content);
+    let content = serde_content::Value::deserialize(deserializer)?;
+    let de = serde_content::Deserializer::new(content.clone()).coerce_numbers();
```
Comment (devongovett) [inline napi/src/transformer.rs:759]: This clone is theoretically cheap if the content contains borrowed data since `serde_content::Value` uses `Cow` internally.

**Review by mischnic — APPROVED** [review]
