### ISSUE TITLE
lightningcss no longer compiles with serde 1.0.220 or above

### ISSUE THREAD

**Issue by colinaaa** [parcel-bundler/lightningcss#1056]
The following error occurs after upgrading to serde 1.0.220+

```
error[E0433]: failed to resolve: could not find `__private` in `serde`
    --> src/properties/mod.rs:992:26
     |
992  |             Content(serde::__private::de::Content<'de>),
     |                            ^^^^^^^^^ could not find `__private` in `serde`
...
1199 | / define_properties! {
1200 | |   "background-color": BackgroundColor(CssColor),
1201 | |   "background-image": BackgroundImage(SmallVec<[Image<'i>; 1]>),
1202 | |   "background-position-x": BackgroundPositionX(SmallVec<[HorizontalPosition; 1]>),
...    |
1615 | |   "color-scheme": ColorScheme(ColorScheme),
1616 | | }
     | |_- in this macro invocation
     |
     = note: this error originates in the macro `define_properties` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Should be related with https://github.com/serde-rs/serde/pull/2608

Similar issue: https://github.com/swc-project/swc/issues/11092
